<?php

/*
 * AstBill  -- Billing, Routing and Management software for Asterisk and MySQL using Drupal
 *
 * www.astbill.com
 *
 * Asterisk -- A telephony toolkit for Linux.
 * Drupal   -- An Open source content management platform.
 *
 * 
 * Copyright (C) 2005, AOFFICE NOMINEE SECRETARIES LIMITED, UNITED KINGDOM.
 *
 * Andreas Mikkelborg <adoroar [Guess What?] astartelecom.com>
 * Are Casilla        <areast  [Guess What?] astartelecom.com>
 *
 *
 * This program is free software, distributed under the terms of
 * the GNU General Public License
 *
 * 2005.01.13 Version 0.9.16
 * 
 */

/* FUNCTIONS:

astcore_search($edit, $posturl)
astcore_printtheme($page_content, $account, $title)
astcore_delete($edit, $deletedmsg, $confirmmsg, $dbquery, $goto, $item)
astcore_list($header, $rows, $noresults, $maxline)

*/


function astcore_help($section='') {
  $output = '';
  switch ($section) {
    case "admin/modules#description":
      $output = t("AstBill Core Functions");
      break;
  }
  return $output;
}


function astcore_search($edit, $posturl) {
	global $user;
	global $db_prefix; 

	$edit = $_POST["edit"];
	$op = $_POST["op"];

	$output = '
<form action="'.$posturl.'" method="post">
<div class="form-item">
<B>'.t('Enter a search string').'&nbsp;&nbsp;</B>
<input type="text" size="20" value="'.$edit['search'].'" name="edit[search]" alt="'.t('Enter a term to search').'" />&#160;
<input type="submit" name="search" value="'.t('Search').'" />&#160;&#160;
</div></form>
';
/*
	$group .= form_textfield($title, 'search', $edit['search'], 30, 30, $description = NULL, $attributes = NULL, $required = FALSE);
	$group .= form_submit('Search');
	
	$output = form($group);
*/	
	return $output;
}


function astcore_printtheme($page_content, $title) {
	$output = '<div class="node "><table width="100%" border="0" cellpadding="0" cellspacing="0"><tr><td class="corner_img_l">&#160;</td><td><h1 class="nodetitle">'.$title.'</h1></td><td class="corner_img_r">&#160;</td></tr></table></div>';

	$output .= '<div class="nodecontent">' . $page_content . "</div>\n";

	print theme("page", $output);
}


function astcore_delete($edit, $deletedmsg, $confirmmsg, $dbquery, $goto, $item) {
	global $user;
	$cid = arg(2);
	$output = '';

	if ($edit) {
		db_query($dbquery);
		//db_query("DELETE FROM {contact_category} WHERE cid = %d and uid = %d", $cid, $user->uid);
		// db_query("DELETE FROM {contact_category} WHERE cid = % d", $edit['cid']);

		// Redirects the response to the list page
		drupal_set_message(t($deletedmsg));
		drupal_goto($goto);
	}

	// Creates a confirmation form
	$categories = astcontact_get_categories();

	$output .= t($confirmmsg);
	$output .= form_hidden('cid', $cid);
	$output .= form_submit(t('Delete'));

	//return form($output);
	$group = form($output);

	$title = t('Remove ').$item;
	$account = $user->uid;
	astcore_printtheme($group, $account, $title);
	//return $output;
}


function astcore_list($header, $rows, $noresults, $maxline) {

	$pager = theme('pager', null, $maxline, 0, tablesort_pager()); 
	if (!empty($pager)) {
		$rows[] = array(array('data' => $pager, 'colspan' => 8));
	}

	$output .= (count($rows) == 0) ? $noresults : theme('table', $header, $rows);
	
	/* ROWS[] EXAMPLE
		$rows[] = array(
		array('data' => $res->date_created, 'align' => 'right'),
		array('data' => $res->dialstatus, 'align' => 'right'),
		array('data' => $res->billtime, 'align' => 'right'));
	*/
	
	
	return $output;
}


function theme_testtable($header, $rows, $attributes = array(), $caption = NULL) {
  $output = '<table'. drupal_attributes($attributes) .">\n";

  if (isset($caption)) {
    $output .= '<caption>'. $caption ."</caption>\n";
  }

  // Format the table header:
  if (count($header)) {
    $ts = tablesort_init($header);
    $output .= ' <thead><tr>';
    foreach ($header as $cell) {
      $cell = tablesort_header($cell, $header, $ts);
      $output .= _theme_table_cell($cell, 1);
    }
    $output .= " </tr></thead>\n";
  }

  // Format the table rows:
  $output .= "<tbody>\n";
  if (count($rows)) {
    foreach ($rows as $number => $row) {
      $attributes = array();

      // Check if we're dealing with a simple or complex row
      if (isset($row['data'])) {
        foreach ($row as $key => $value) {
          if ($key == 'data') {
            $cells = $value;
          }
          else {
            $attributes[$key] = $value;
          }
        }
      }
      else {
        $cells = $row;
      }

      // Add odd/even class
      $class = ($number % 2 == 1) ? 'even': 'odd';
      if (isset($attributes['class'])) {
        $attributes['class'] .= ' '. $class;
      }
      else {
        $attributes['class'] = $class;
      }

      // Build row
      $output .= ' <tr'. drupal_attributes($attributes) .'>';
      $i = 0;
      foreach ($cells as $cell) {
        $cell = tablesort_cell($cell, $header, $ts, $i++);
        $output .= _theme_table_cell($cell, 0);
      }
      $output .= " </tr>\n";
    }
  }

  $output .= "</tbody></table>\n";
  return $output;
}



?>
