<?php

/*
 * AstBill  -- Billing, Routing and Management software for Asterisk and MySQL using Drupal
 *
 * www.astbill.com
 *
 * Asterisk -- A telephony toolkit for Linux.
 * Drupal   -- An Open source content management platform.
 *
 * 
 * Copyright (C) 2005,2006 AOFFICE NOMINEE SECRETARIES LIMITED, UNITED KINGDOM.
 *
 * Andreas Mikkelborg <adoroar [Guess What?] astartelecom.com>
 * Are Casilla        <areast  [Guess What?] astartelecom.com>
 *
 *
 * This program is free software, distributed under the terms of
 * the GNU General Public License
 *
 * 2006 May 07 Version 0.9.18
 * 
 */

// &#229;  = å
// &#248;  = ø
// &#230;  = æ



function astpartneradmin_help($section='') {
  $output = '';
  switch ($section) {
    case "admin/modules#description":
      $output = t("AstBill Partner Admin");
      break;
  }
  return $output;
} // function astentry_help


function astpartneradmin_menu($may_cache) {
	$items = array();
	$access = user_access('astpartner admin module');

	$items[] = array('path' => 'astpartneradm', 'title' => t('Partner Admin'),
	'callback' => 'astpartneradmin_main',
	'access' => $access);

  	$items[] = array('path' => 'astpartneradm/users', 'title' => t('Web Users'),
	'callback' => 'astpartneradmin_webuser',
	'access' => $access);

  	$items[] = array('path' => 'astpartneradm/usercreate', 'title' => t('Create User'),
	'callback' => 'astpartneradmin_user_create',
	'access' => $access);

	$items[] = array('path' => 'astpartneradm/useredit', 'title' => t('Edit User'),
	'callback' => 'astpartneradmin_user_edit',
	'access' => $access,
	'type' => MENU_CALLBACK);

/*      	$items[] = array('path' => 'astbilladm/orders/info', 'title' => t('Detailed'),
		'callback' => 'astorders_info',
		'access' => $access,
		'type' => MENU_CALLBACK);
*/
  return $items;
}

// astpartneradmin_user_create

/**
* Valid permissions for this module
* @return array An array of valid permissions for the astentry module
* At this point, we'll give permission to anyone who can access site content 
* or administrate the module:
*/


function astpartneradmin_perm() {
	return array('astpartner admin module');
}


function astpartneradmin_main() {
	global $user;
	global $db_prefix; 
	$edit = $_POST["edit"];
	$op = $_POST["op"];


	switch ($op) {
		case t('Search'):
		$output .= astpartneradmin_list($value, $edit);
		break;
		default:
		
		$value = $edit['search'];
		$tmp = astcore_flattenArray($_GET);
		
		if (!empty($tmp['searchedit'])) {
			$value = $tmp['searchedit'];
		}
		
		$output = astcore_search($edit, $posturl = url('astpartneradm'), $value);
		$output .= astpartneradmin_list($value, $edit);
	}
	
	$title = 'View';
	astcore_printtheme($output, $title);
}

function astpartneradmin_list($value, $edit) {
	global $user;
	global $db_prefix;
	$maxline = 40;
		
	$header = array(
	array('data' => t('User'), 'field' => 'name'),
	array('data' => t('UID'), 'field' => 'uid'),
	array('data' => t('Account'), 'field' => 'accountcode', 'sort' => 'asc'),
//	array('data' => t('Pass')),
	array('data' => t('Type'), 'field' => 'tech'),
	array('data' => t('Name'), 'field' => 'accountname'),
	array('data' => t('Balance')),
	array('data' => t('Expenditure')),
	array('data' => t('Payments')),
	array('data' => t('Calls')),
	array('data' => t('Operations'), 'colspan' => 4));

	$partnerid = astcore_partnerid();

// $partnerid = "30005";

/*	$sql = "SELECT accountcode, tech, secret, startingcredit, usr.uid, usr.name, LEFT(accountname,5) accountname FROM astaccount, {users} usr WHERE astaccount.uid = usr.uid AND db_prefix ='".$db_prefix."' AND tech IN (select actype from astactype where active = '1' ) AND CONCAT_WS(',', accountcode, tech, usr.uid, LOWER('usr.name'), accountname, usr.name) LIKE LOWER('%".$value."%')". tablesort_sql($header);
*/	
	$sql = "SELECT accountcode, tech, secret, startingcredit, usr.uid, usr.name, LEFT(accountname,5) accountname, partnerid FROM astaccount aa, astuser au, cbk_users usr WHERE partnerid = '".$partnerid."' and aa.uid = au.uid and aa.uid = usr.uid AND aa.db_prefix = 'cbk_' AND aa.db_prefix = au.db_prefix AND tech IN (select actype from astactype where active = '1')  AND CONCAT_WS(',', accountcode, tech, usr.uid, LOWER('usr.name'), accountname, usr.name) LIKE LOWER('%".$value."%')". tablesort_sql($header);


	$result = pager_query($sql, $maxline);
	
	while ($res = db_fetch_object($result)) {
		$sumpaid = db_fetch_object(db_query("SELECT round(Sum(astpayment.paidamount), 2) AS sumpaid FROM astpayment WHERE astpayment.accountcode = '%s'", $res->accountcode));
		
		$cdrcost = db_fetch_object(db_query("SELECT round((Sum(astcdr.price)/100),2) AS sumprice FROM astcdr where dialstatus like 'ANSWER%%' and answeredtime <> 0 and trunk <> 'Local' AND accountcode = '%s'", $res->accountcode));
		
		$countcalls = db_fetch_object(db_query("SELECT count(*) AS countcalls FROM astcdr where dialstatus like 'ANSWER%%' and answeredtime <> 0 and trunk <> 'Local' AND accountcode = '%s'", $res->accountcode));
		
		if (empty($sumpaid->sumpaid)) {$sumpaid->sumpaid = 0;}
		if (empty($cdrcost->sumprice)) {$cdrcost->sumprice = 0;}
		if (empty($countcalls->countcalls)) {$countcalls->countcalls = 0;}
		
		$sumbalance =  number_format(($sumpaid->sumpaid + $res->startingcredit - $cdrcost->sumprice), 2);
		$sql = db_fetch_object(db_query("select value from astsystem where name = 'TopUpURL' and serverid = 'DEF'"));
		
		$rows[] = array(
		'<A HREF="'.url('user/'.$res->uid).'">'.$res->name.'</A>',
		$res->uid,
		'<A TITLE="Password: '.$res->secret.'" HREF="'.url('astbilladm/editaccount/'.$res->accountcode).'">'.$res->accountcode.'</B>' . '</A>',
	
	//	$res->secret,  
		'<IMG BORDER="0" SRC="files/astar/'.$res->tech.'.gif">',
		$res->accountname, 
		
	        array('data' => '<B>'.$sumbalance.'</B>', 'align' => 'right'), // Balance
		array('data' => $cdrcost->sumprice, 'align' => 'right'), // Expenditure
		array('data' => $sumpaid->sumpaid, 'align' => 'right'), // Payments
		array('data' => $countcalls->countcalls.'&nbsp;&nbsp;', 'align' => 'right'), // Calls
		
		'<a href="'.url('astpbx/account/'.$res->accountcode).'"><img border="0" src="files/astar/view.gif"></a>',
		'<a href="'.url('astbilladm/editaccount/'.$res->accountcode).'"><img border="0" src="files/astar/edit.gif"></a>'
	//	'<a href="'.$sql->value.$res->accountcode.'"><img border="0" src="files/astar/topup.gif"></a>'
	//	'<a href="'.url('astbilladm/removeaccount/'.$res->uid.'/'.$res->accountcode).'">'.t('Remove').'</a>'
		);
	}

  
	$output = astcore_list($header, $rows, $noresults = t('No Accounts for this User.'), $maxline);
	return $output;
}

function astpartneradmin_webuser() {
	global $user;
	global $db_prefix; 
	$edit = $_POST["edit"];
	$op = $_POST["op"];

	switch ($op) {
		case t('Search'):
		$output .= astpartneradmin_webuser_list($value, $edit);
		break;
		default:
		
		$value = $edit['search'];
		$tmp = astcore_flattenArray($_GET);
		
		if (!empty($tmp['searchedit'])) {
			$value = $tmp['searchedit'];
		}
		
		$output = astcore_search($edit, $posturl = url('astpartneradm/users'), $value);
		$output .= astpartneradmin_webuser_list($value, $edit);
	}
	
	$title = 'View';
	astcore_printtheme($output, $title);
}

function astpartneradmin_webuser_list($value, $edit) {
	global $user;
	global $db_prefix;
	$maxline = 40;
		
	$header = array(
	array('data' => t('User'), 'field' => 'name'),
	array('data' => t('UID'), 'field' => 'uid', 'sort' => 'desc'),
	array('data' => t('Created')),
	array('data' => t('mail'))
	//array('data' => t('Operations'), 'colspan' => 2)
	);

	$partnerid = astcore_partnerid();

	$sql = "SELECT usr.uid, astuser.partnerid, usr.name, usr.mail, date(astuser.timestamp) created FROM {users} usr INNER JOIN astuser ON usr.uid = astuser.uid WHERE partnerid = '".$partnerid."' and astuser.db_prefix = '".$db_prefix."' AND CONCAT_WS(',', usr.uid, LOWER('usr.name'), LOWER('usr.mail')) LIKE LOWER('%".$value."%')". tablesort_sql($header);


	$result = pager_query($sql, $maxline);
	
	while ($res = db_fetch_object($result)) {
		
		$rows[] = array(
		'<A HREF="'.url('astpartneradm/useredit/'.$res->uid).'">'.$res->name.'</A>'.'&nbsp;&nbsp;',
		'<A HREF="'.url('astpartneradm/useredit/'.$res->uid).'">'.$res->uid.'</A>',
//		'<IMG BORDER="0" SRC="files/astar/'.$res->tech.'.gif">',
		$res->created.'&nbsp;&nbsp;', 
		$res->mail, 

/*		array('data' => $countcalls->countcalls.'&nbsp;&nbsp;', 'align' => 'right'), // Calls
		'<a href="'.url('astbilladm/editaccount/'.$res->uid).'"><img border="0" src="files/astar/edit.gif"></a>'
*/
		);

	}
  
	$output = astcore_list($header, $rows, $noresults = t('No Users for Partner.'), $maxline);
	return $output;
}

function astpartneradmin_user_create() {
  global $user, $base_url;
  $edit = $_POST["edit"];
  $op = $_POST["op"];

  if ($_POST['op'] == t('Create') || $_POST['op'] == t('Back')) {
			astpartneradmin_user_save($_POST['edit']);
	        drupal_goto("astpartneradm/users");
  }   else {
    $output = astpartneradmin_user_form();
  }

	$title = 'Partners Web User Informasjon';
	astcore_printtheme($output, $title);	
}

function astpartneradmin_user_save($edit) {
  global $user;
  global $db_prefix; 
 
  $myerror = 0;
  $errors = array();

/*  if  (empty($edit['future'])) {
		  $errors['future'] = t('Abonnement inneholder ulovlige/ingen tegn');
		  $myerror = 1;
  }  */
  if (empty($edit['firstname'])) {
   // form_set_error('src', t('The system path %path is invalid.', array('%path' => theme('placeholder', $src))));
   		  $errors['firstname'] = t('Firstname have no characters');
		  $myerror = 1;
  }
  if  (empty($edit['lastname'])) {
		  $errors['lastname'] = t('Lastname have no characters');
		  $myerror = 1;
  }
  if  (empty($edit['zip'])) {
		  $errors['zip'] = t('Zip have no characters');
		  $myerror = 1;
  }
  if  (empty($edit['place'])) {
		  $errors['place'] = t('Place have no characters');
		  $myerror = 1;
  }

  if  (empty($edit['password'])) {
		  $errors['password'] = t('Password have no characters');
		  $myerror = 1;
  }


$tmpuser = user_load(array('mail' => $edit['email']));
if ($edit['email'] ==$tmpuser->mail ) {
	$errors['email'] = t('E-mail is in use!');
    $myerror = 1;
}

$name = $edit['firstname']."_".$edit['lastname'];
$tmpuser = user_load(array('name' => $name));

if ($name == $tmpuser->name ) {
//	drupal_set_message("fun");
	
	$name = $edit['firstname'].$edit['lastname'];

    $tmpuser = user_load(array('name' => $name));
	if ($name == $tmpuser->name ) {
		$name = $edit['firstname']."_".$edit['lastname'].substr(Rand(),-4);
		 $tmpuser = user_load(array('name' => $name));
		  if ($name == $tmpuser->name ) {
			$errors['Name'] = t('ERROR: Name is used');
			$myerror = 1;
		  }
	}

}

// drupal_set_message(substr(Rand(),-4));

if ($myerror == 1) {
	  foreach ($errors as $name => $message) {
		form_set_error($name, $message);
	  } 
	 return astpartneradmin_user_form($edit);
} else {

$partnerid = astcore_partnerid();
if (is_numeric(arg(2))) {
	$partnerid = arg(2);
}


//  $wwwpw = user_password();

$newuser = user_save('', array('name' => $name, 'pass' => $edit['password'], 'init' => $edit['email'], 'mail' => $edit['email'],'status' => 1, 'roles' => array(_user_authenticated_id())));

 watchdog('user', t('New Partner created user: %user.', array('%user' => theme('placeholder', $name))), WATCHDOG_NOTICE, l(t('edit'), 'user/'. $user->uid .'/edit'));



db_query("UPDATE astuser set partnerid = '%s', firstname='%s', lastname='%s', address1='%s', zip='%s', city='%s', country='%s', mobile='%s',birthdate2='".$edit['day']."/".$edit['month']."/".$edit['year']."',valuecode='%s' where uid = $newuser->uid and db_prefix='%s'", $partnerid,
$edit['firstname'], $edit['lastname'], $edit['address1'], $edit['zip'], $edit['place'], "Norway", $edit['mobile'],$edit['valuecode'],$db_prefix);

if ($partnerid == '30005' and $db_prefix = 'cbk_') {  // WARNING - Just Temporary
	db_query("update cbk_users_roles set rid = '6' where uid = ".$newuser->uid);
}   
if ($partnerid == '130016' and $db_prefix = 'cbk_') {  // WARNING - Just Temporary
	db_query("update cbk_users_roles set rid = '6' where uid = ".$newuser->uid);
}   

drupal_set_message(t('User '.$name.' Created with id: '.$newuser->uid));

}
}

function astpartneradmin_user_form() {
	global $user;
	global $db_prefix; 
	$edit = $_POST["edit"];
    $op = $_POST["op"];

if (arg(1) == 'useredit'){ // START CHECK IF PartnerCHANGE

$sql = db_query("SELECT company, firstname, lastname, contactperson, address1, address2, zip, city, state, countrycode, mobile, phonework, fax,email,comment,customerstatus,active FROM astpartner WHERE pid = '%s' and db_prefix ='".$db_prefix."'", arg(3));
$sqlout = db_fetch_object($sql);

	$firstname = $sqlout->firstname;
	$lastname = $sqlout->lastname;
	$address1 = $sqlout->address1;
	//$address2 = $sqlout->address2;
	$zip = $sqlout->zip;
	$city = $sqlout->city;
	//$state = $sqlout->state;
	$country = $sqlout->countrycode;
	$mobile = $sqlout->mobile;
	//$phonework = $sqlout->phonework;
	//$fax = $sqlout->fax;
	$comment = $sqlout->comment;
	$customerstatus = $sqlout->customerstatus;
	$active = $sqlout->active;


}// User Edit


	$group .= astcore_form_start();
	$group .= astcore_form_textfield(t("Firstname"), "firstname", $firstname, 30, 100);
	$group .= astcore_form_textfield(t("Lastname"), "lastname", $lastname, 30, 100);
	$group .= astcore_form_textfield(t('Address1'), 'address1', $address1, 30, 100);
//	$group .= astcore_form_textfield(t('Address2'), 'address2', $address2, 30, 100);
	$group .= astcore_form_textfield(t('Zip'), 'zip', $zip, 30, 100);
	$group .= astcore_form_textfield(t('Place'), 'place', $place, 30, 100);
	$group .= astcore_form_textfield(t('mobile'), 'mobile', $mobile, 30, 100);
	$group .= astcore_form_textfield(t('E-mail'), 'email', $email, 30, 100);
	$group .= astcore_form_textfield(t('Password'), 'password', $password, 30, 100);
	$group .= astcore_form_textfield(t('Valuecode'), 'valuecode', $valuecode, 30, 100);
    $group .= astcore_form_end();
	
	

if (arg(1) == 'usercreate'){
	$group .= form_submit(t('Create'));
} else {
	$group .= form_submit(t('Change'));
}
	$group .= form_submit(t('Back'));
	//$form = form_group(t('Account details'), $group);
	return form($group);
}


function astpartneradmin_user_simpleform($userid) {
	global $user;
	global $db_prefix; 
	$edit = $_POST["edit"];
    $op = $_POST["op"];

  // Make sure you don't trust the URL to be safe! Always check for exploits.
  //if (!is_numeric($alice) || !is_numeric($bob)) {
  if (!is_numeric($userid)) {
    // We will just show a standard "access denied" page in this case.
    drupal_access_denied();
    return;
  }

$partnerid = astcore_partnerid();

// if (arg(1) == 'useredit'){ 

$SQL = "SELECT name, firstname, lastname, mail FROM cbk_users, astuser WHERE astuser.db_prefix = 'cbk_' and cbk_users.uid = astuser.uid and astuser.uid = %s and partnerid = '%s'";

$sqlfetch = db_query($SQL, $userid,$partnerid);
//$sqlfetch = db_query($SQL);
$sqlout = db_fetch_object($sqlfetch);

// }// User Edit


	$group .= astcore_form_start();
	$group .= astcore_form_textfield(t("Username"), "name", $sqlout->name, 30, 100);

//	$group .= astcore_form_textfield(t("Firstname"), "firstname", $sqlout->firstname, 30, 100);
//	$group .= astcore_form_textfield(t("Lastname"), "lastname", $sqlout->lastname, 30, 100);

//	$group .= astcore_form_textfield(t('Address1'), 'address1', $address1, 30, 100);
//	$group .= astcore_form_textfield(t('Address2'), 'address2', $address2, 30, 100);
//	$group .= astcore_form_textfield(t('Zip'), 'zip', $zip, 30, 100);
//	$group .= astcore_form_textfield(t('Place'), 'place', $place, 30, 100);
//	$group .= astcore_form_textfield(t('mobile'), 'mobile', $mobile, 30, 100);
	
	$group .= astcore_form_textfield(t('E-mail'), 'mail', $sqlout->mail, 30, 100);

//	$group .= astcore_form_textfield(t('Password'), 'password', "", 30, 100);

//	$group .= astcore_form_textfield(t('Valuecode'), 'valuecode', $valuecode, 30, 100);
    $group .= astcore_form_end();
	
	

if (arg(1) == 'usercreate'){
	$group .= form_submit(t('Create'));
} else {
	$group .= form_submit(t('Change'));
}
	$group .= form_submit(t('Back'));
	//$form = form_group(t('Account details'), $group);
	return form($group);
}


function astpartneradmin_user_edit() {
  global $user;
  global $db_prefix; 

  $edit = $_POST["edit"];
  $op = $_POST["op"];

  switch (($op ? $op : arg(1))) {
    case t('Change'):
      $title = t('Edit Account');
   //   if (astpartner_Partner_validate($edit)) {
        astpartneradmin_simpleuser_save($edit,arg(2));
        drupal_goto("astpartneradm/users");
    //  } else {
	//	drupal_goto("astpartneradm/useredit/".arg(3));
	//  }
      break;
  	case t('Back'):
		drupal_goto("astpartneradm/users");
    default:
	  $output = astpartneradmin_user_simpleform(arg(2));
  }


	$title = t('Change');
	astcore_printtheme($output, $title);	
}

function astpartneradmin_simpleuser_save($edit, $userid) {
  global $user;
  global $db_prefix; 
 
  $myerror = 0;
  $errors = array();

    // Make sure you don't trust the URL to be safe! Always check for exploits.
  //if (!is_numeric($alice) || !is_numeric($bob)) {
  if (!is_numeric($userid)) {
    // We will just show a standard "access denied" page in this case.
    drupal_access_denied();
    return;
  }


 // if (empty($edit['firstname'])) {
 //  		  $errors['firstname'] = t('Firstname have no characters');
//		  $myerror = 1;
 // }
//  if  (empty($edit['lastname'])) {
//		  $errors['lastname'] = t('Lastname have no characters');
//		  $myerror = 1;
//  }


// $tmpuser = user_load(array('uid' => $userid));

//drupal_set_message($tmpuser=>name);

$partnerid = astcore_partnerid();

$sqlfetch = db_query("select uid, partnerid from astuser where db_prefix = '%s' and uid = '%s'", $db_prefix, $userid);
$sqlout = db_fetch_object($sqlfetch);

// To ensure we only update this partners users
if ($sqlout->partnerid == $partnerid) {
	//  $wwwpw = user_password();
	//$newuser = user_save($tmpuser, array('name' => $name, 'mail' => $edit['email']));
	$sqlfetch = db_query("UPDATE {users} set name = '%s', mail='%s' where uid = '%s'", $edit['name'], $edit['mail'], $userid);
	drupal_set_message(t('User '.$name.' Updated id: '.$userid));
}



}