<?php

/*
 * AstBill  -- Billing, Routing and Management software for Asterisk and MySQL using Drupal
 *
 * www.astbill.com
 *
 * Asterisk -- A telephony toolkit for Linux.
 * Drupal   -- An Open source content management platform.
 *
 * 
 * Copyright (C) 2006, CBK TELE AS, OSLO, NORWAY.
 *
 * Andreas Mikkelborg <adoroar [Guess What?] astartelecom.com>
 * Are Casilla        <areast  [Guess What?] astartelecom.com>
 * Uvarajan	      <areast  [Guess What?] astartelecom.com>
 * Komathi	      <areast  [Guess What?] astartelecom.com>
 *
 *
 * This program is free software, distributed under the terms of
 * the GNU General Public License
 *
 * 2006.12.05 Version 0.9.20
 * 
 */


function astaccountcode_help($section='') {
  $output = '';
  switch ($section) {
    case "admin/modules#description":
      $output = t("List / Search Accountcode");
      break;
  }
  return $output;
} // function astentry_help


function astaccountcode_menu($may_cache) {
	$items = array();
	$access = user_access('astaccountcode module');
     
   	$items[] = array('path' => 'astglobal/voip/accountcode', 'title' => t('Accountcode'),
	'callback' => 'astaccountcode_main',
	'access' => $access);

/*
	$items[] = array('path' => 'astglobal/voip/accountcode', 'title' => t('Add Subscribers'),	
	'callback' => 'astaccountcode_tech',
	'access' => $access);
*/
	return $items;

}


/**
* Valid permissions for this module
* @return array An array of valid permissions for the astentry module
* At this point, we'll give permission to anyone who can access site content 
* or administrate the module:
*/


function astaccountcode_perm() {
	return array('astaccountcode module');
}

function astaccountcode_main() {

	global $user;
	global $db_prefix;
	$edit = $_POST["edit"];
	$param = arg(3);
	$args = arg(4);
	//echo $args;
	$posturl ="astglobal/voip/accountcode/";
	if ($args==""){
	$output .= astcore_search($edit, $posturl = url($posturl.$param), $value, 'NO');
	}
	$output .= astaccountcode_list($edit, $value, $param);
	$title = t('Show Accountcodes');
	astcore_printtheme($output, $title);
}
function astaccountcode_list($value, $edit, $param) {
	global $user;
	global $db_prefix;
	$edit = $_POST["edit"];
	$op = $_POST["op"];

	$value = trim($value);
	$search = trim($edit['search']);
	
	$maxline = 40;
		
  	$header = array(
  	array('data' => t('Usr'), 'field' => 'uid'),
	array('data' => t('Pid'), 'field' => 'pid'),
	array('data' => t('Tech'), 'field' => 'tech'),
	array('data' => t('Account'), 'field' => 'accountcode'),
	array('data' => t('Stat'), 'colspan' => 1),
	//array('data' => t('Password')),
	array('data' => t('Callerid'), 'field' => 'callerid'),
	array('data' => t('CLIP'), 'field' => 'forcecallerid'),
	array('data' => t('Serverid'), 'field' => 'serverid'),
	array('data' => t('RPID'), 'field' => 'trustrpid'),
//	array('data' => t('Ops'), 'colspan' => 1),
	array('data' => t('IP'), 'colspan' => 1),
	array('data' => t('Refreshed'), 'colspan' => 1),
	array('data' => t('Accountname'), 'colspan' => 1),
	//array('data' => t(''), 'colspan' => 1)
	);
    
	//$value = arg(3);                                                                                 
	if ($search==""){
  		$SQL = "SELECT pa.pid,ac.uid,ac.accountcode,ac.secret,ac.callerid,ac.forcecallerid,ac.tech,ac.active, ac.serverid,ac.trustrpid,fullcontact, CONCAT_WS(':',ac.ipaddr,ac.port) ip, ac.reg_changed,accountname FROM astaccount ac, astuser us,astpartner pa WHERE ac.uid = us.uid and ac.db_prefix = us.db_prefix and   us.partnerid = pa.pid and ac.tech in (select actype from astactype where astactype.active = '1')". tablesort_sql($header);
	}
	if ($search!=""){
		$SQL = "SELECT pa.pid,ac.uid,ac.accountcode,ac.secret,ac.callerid,ac.forcecallerid,ac.tech,ac.active, ac.serverid,ac.trustrpid,fullcontact, CONCAT_WS(':',ac.ipaddr,ac.port) ip, ac.reg_changed,accountname FROM astaccount ac, astuser us LEFT JOIN astpartner pa ON us.partnerid = pa.pid WHERE ac.uid = us.uid and ac.db_prefix = us.db_prefix and ac.tech in (select actype from astactype where astactype.active = '1') and CONCAT_WS(',', ac.db_prefix,ac.accountcode,pa.pid,LOWER(ac.callerid),LOWER(ac.forcecallerid),LOWER(ac.serverid), LOWER(ac.accountname),ac.ipaddr,ac.port) LIKE LOWER('%".$search."%')". tablesort_sql($header);
	}

  $result = pager_query($SQL, $maxline);
  
  while ($res = db_fetch_object($result)) {

	if ($res>active == 1){ $imagename = "green_dott1.gif";
	} else { $imagename = "red_dott1.gif"; }

	$rows[] = array(
		$res->uid."&nbsp;",
		$res->pid."&nbsp;",
		$res->tech."&nbsp;",
		$res->accountcode."&nbsp;",
		array('data' => "<IMG BORDER=\"0\" src=\"files/astar/$imagename\">", 'align' => 'center'),
		//$res->secret."&nbsp;",
		$res->callerid."&nbsp;",
		$res->forcecallerid."&nbsp;",
		$res->serverid."&nbsp;",
		$res->trustrpid."&nbsp;",
		//'<A HREF="'.url('astglobal/tech/change/'.$res->accountcode.'/'.$res->pid).'"><IMG BORDER="0" src="files/astar/edit.gif"></A>',
		// $res->ip,fullcontact
       		 array('data' => $res->ip, 'title' => $res->fullcontact),
		//	title="Password: '.$res->secret.'"
		$res->reg_changed,
		$res->accountname,
	);
  }
	$output = astcore_list($header, $rows, $noresults = t('No Search Results.'), $maxline);
	return $output;
}
