<?php

/*
 * AstBill  -- Billing, Routing and Management software for Asterisk and MySQL using Drupal
 *
 * www.astbill.com
 *
 * Asterisk -- A telephony toolkit for Linux.
 * Drupal   -- An Open source content management platform.
 *
 * 
 * Copyright (C) 2006, CBK TELE AS, OSLO, NORWAY
 *
 * Andreas Mikkelborg <adoroar [Guess What?] astartelecom.com>
 * Are Casilla        <areast  [Guess What?] astartelecom.com>
 * Uvarajan	      <areast  [Guess What?] astartelecom.com>
 *
 *
 * This program is free software, distributed under the terms of
 * the GNU General Public License
 *
 * 2006.12.05 Version 0.9.20
 * 
 */

// &#229;  = å
// &#248;  = ø
// &#230;  = æ



function astmsnall_help($section='') {
  $output = '';
  switch ($section) {
    case "admin/modules#description":
      $output = t("MSN Unused and Used Module");
      break;
  }
  return $output;
} // function astentry_help


function astmsnall_menu($may_cache) {
	$items = array();
	$access = user_access('astmsnall module');
	
	$items[] = array('path' => 'astglobal/voip/msnall/search', 'title' => t('MSN All'),
	'callback' => 'astmsnall_msnsearch',
	'access' => $access);
	
	$items[] = array('path' => 'astglobal/voip/msnnotused', 'title' => t('MSN Unused'),	
	'callback' => 'astmsnall_search',
	'access' => $access);

	return $items;
}


/**
* Valid permissions for this module
* @return array An array of valid permissions for the astentry module
* At this point, we'll give permission to anyone who can access site content 
* or administrate the module:
*/


function astmsnall_perm() {
	return array('astmsnall module');
}

function astmsnall_msnsearch() {
    $edit = $_POST['edit']; 
	$values = arg(3);   
	if ($values=="search"){
	 $posturl ="astglobal/voip/msnall/search/";
	 $output .= astcore_search($edit, $posturl = url($posturl.$param), $value, 'YES');
	 $SQL = "Select did,acgroup,fylkekode from astacdid order by fylkekode,did";
	 $res = db_fetch_object(db_query($SQL));
	 $output .= astmsnall_msn_searchlist($value, $edit);
 	 $title = t('MSN Search');
	 $overmenu = array();
	 astcore_printtheme($output, $title, $undermenu = 'FALSE', $undermenutitle = 'FALSE', $overmenu);
	 return $output;
	}
}

function astmsnall_msn_searchlist($value, $edit) {
	global $user;
	global $db_prefix;
	$value = Trim($value);
	$maxline = 40;
	$search = Trim($edit['search']);
			
	  $header = array(
	    array('data' => t('db'), 'field' => 'prefix'),
	    array('data' => t('Usr'), 'field' => 'uid'),
	    array('data' => t('MSN'), 'field' => 'did', 'sort' => 'asc'),
	    array('data' => t('Partner'), 'field' => 'pid'),
	    array('data' => t('Group'), 'field' => 'acgroup'),
	    array('data' => t('Forward'), 'field' => 'forwardto'),
	    array('data' => t('A')),
	    array('data' => t('Porting Date'), 'field' => 'portindate'),
	    array('data' => t('Zipcode'), 'field' => 'zipcode'),
	    array('data' => t('Batch'), 'colspan' => 1),
	    array('data' => t('Status')),
	    array('data' => t('Remarks'), 'colspan' => 1),
	  );

    
  $value = arg(3);     
  if($search == ""){
   $SQL = "SELECT left(did.db_prefix,3) prefix, did.uid,did.did,did.acgroup,did.forwardto,did.active, did.portindate,did.zipcode,did.batchno,did.remarks,pa.pid FROM astacdid did LEFT JOIN astuser us ON  (did.uid = us.uid and did.db_prefix = us.db_prefix) LEFT JOIN astpartner pa ON pa.pid = us.partnerid". tablesort_sql($header);  

   $sqlCount = "select count(*) FROM astacdid did LEFT JOIN astuser us ON  (did.uid = us.uid and did.db_prefix = us.db_prefix) LEFT JOIN astpartner pa ON pa.pid = us.partnerid";

  }
  
  if($search != "") {
    $SQL = "SELECT left(did.db_prefix,3) prefix, did.uid,did.did,did.acgroup,did.forwardto,did.active, did.portindate,did.zipcode,did.batchno,did.remarks,pa.pid FROM astacdid did LEFT JOIN astuser us ON  (did.uid = us.uid and did.db_prefix = us.db_prefix) LEFT JOIN astpartner pa ON pa.pid = us.partnerid where CONCAT_WS(',', did.did, did.db_prefix,did.forwardto,pa.pid,did.uid,LOWER(did.acgroup),LOWER(did.zipcode),LOWER(did.remarks),did.portindate) LIKE LOWER('%".$search."%')". tablesort_sql($header);
	
	$sqlCount = "select count(*) FROM astacdid did LEFT JOIN astuser us ON  (did.uid = us.uid and did.db_prefix = us.db_prefix) LEFT JOIN astpartner pa ON pa.pid = us.partnerid where CONCAT_WS(',', did.did, did.db_prefix,did.forwardto,pa.pid,did.uid,LOWER(did.acgroup),LOWER(did.zipcode),LOWER(did.remarks),did.portindate) LIKE LOWER('%".$search."%')";


	// did.did like '".$search."%'". tablesort_sql($header);
  }
  $result = pager_query($SQL, $maxline, 0, $sqlCount);
  
  while ($res = db_fetch_object($result)) {
  			if($res->active == 1){
				$imagename = "green_dott1.gif";
			}else{
				$imagename = "red_dott1.gif";
			}

	$rows[] = array(
		$res->prefix."&nbsp;",
		$res->uid."&nbsp;",
		$res->did."&nbsp;",
		$res->pid."&nbsp;",
		$res->acgroup."&nbsp;",
		$res->forwardto."&nbsp;",
		$res->active."&nbsp;",
		$res->portindate."&nbsp;",
		$res->zipcode,
		$res->batchno,
		array('data' => "<IMG BORDER=\"0\" src=\"files/astar/$imagename\">", 'align' => 'center'),
	//	"<IMG BORDER=\"0\" src=\"files/astar/$imagename\">",
		$res->remarks,
	);
  }
	$output = astcore_list($header, $rows, $noresults = t('No MSN Numbers'), $maxline);
	return $output;
}


function astmsnall_search() {
	global $user;
	global $db_prefix;
	$posturl = "astglobal/voip/msnnotused/";
	$edit = $_POST['edit'];
	$op = $_POST['op'];
	$value = Trim($edit['search']);
	$param = Trim($edit['status']);
	$customerstatus = Trim($edit['customerstatus']);
	//echo $customerstatus;
	$tmp = astcore_flattenArray($_GET);
	
	if (!empty($tmp['searchedit'])) {
		$value = $tmp['searchedit'];
	}

	$param = arg(3);
	$search = arg(4);
	
	if (empty($param)) {
		$param = 'all';
		drupal_goto($posturl.$param);
	}
	if ($value!="")
	{
		$param = $value;
	}

	$partnerid = astcore_partnerid();
	$statusopts['all'] = t('fylkekode');
	
	$overmenu = array(url('astpbx/ccorders/create/').'">');
	$output = '<form action="'.$posturl.'" method="post">';
	$output .= '<table border="0" width="100%"><tr><td width="13%">';
	$manufacturerValue = db_query("select fylkekode from astacdid where fylkekode <> '' order by fylkekode"); 
	while ($manufacture = db_fetch_object($manufacturerValue)) {

	$mtypes_display[$manufacture->fylkekode] = $manufacture->fylkekode; } 
	$output .= form_select(t('Fylkekode'), 'customerstatus', $edit->customerstatus, $mtypes_display);
	
	$output .='</td><td><input type="submit" name="Go" value="'.t('Go').'" />&#160;&#160;</td></tr></table></form>';
	$output .= astcore_search($edit, $posturl = url($posturl.$param), $value, 'NO');

	if ($param == 'all') { $param = '%';}
	$output .= astmsnall_list_search($edit, $value, $param);
	$output = form($output);

	$title = t('View MSN Unused');
	astcore_printtheme($output, $title, $undermenu = 'FALSE', $undermenutitle = 'FALSE', $overmenu);
}

function astmsnall_list_search($edit, $value, $param = '%') {
	global $user;
	global $db_prefix;

	$edit = $_POST["edit"];
	$op = $_POST["op"];
    $value = "";
	$maxline = 40;
	$value = Trim($edit['search']);
	
	$customerstatus = $edit['customerstatus'];
	
	  $header = array(
	    array('data' => t('Did'), 'field' => 'did', 'sort' => 'asc'),
	    array('data' => t('acgroup'), 'field' => 'acgroup'),
	    array('data' => t('fylkekode'), 'field' => 'fylkekode'),
		array('data' => t('Status')),
	     );
	
	$SQL = "Select did,acgroup,fylkekode,active from astacdid where uid = 0". tablesort_sql($header);
	$sqlCount = "Select count(*) from astacdid where uid = 0";
	$result = pager_query($SQL, $maxline, 0, $sqlCount);

	if ($param != "" && $value == "" && $customerstatus =="") {
		while ($item = db_fetch_object($result)){
  			if($item->active == 1){
				$imagename = "green_dott1.gif";
			}else{
				$imagename = "red_dott1.gif";
			}

	        $rows[] = array(
			$item->did.'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $item->acgroup.'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $item->fylkekode.'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
			array('data' => "<IMG BORDER=\"0\" src=\"files/astar/$imagename\">", 'align' => 'center'),
		);
	    }
		$output = astcore_list($header, $rows, $noresults = t('No MSN Numbers for Partner.'), $maxline);
		return $output;
	}
	
	if ($param != "" && $value != "" )
	{ 
	  	 $value = Trim($value)."%";
	  	 $newvalue = $value;	  	  	 
	  	 $sql = "select did,acgroup,fylkekode,active from astacdid where did like '".$newvalue."'". tablesort_sql($header);
	     $sqlCount = "select count(*) from astacdid where did like '".$newvalue."'";
	     $result = pager_query($sql, $maxline, 0, $sqlCount);
		   while ($item = db_fetch_object($result)) {
				if($item->active == 1){
					$imagename = "green_dott1.gif";
				}else{
					$imagename = "red_dott1.gif";
				}

         	 $rows[] = array(   
				$item->did.'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',  $item->acgroup.'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
				$item->fylkekode.'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
			    array('data' => "<IMG BORDER=\"0\" src=\"files/astar/$imagename\">", 'align' => 'center'),
		   );
		   }
	$output = astcore_list($header, $rows, $noresults = t('No MSN Numbers'), $maxline);
	return $output;

	}

	if ($param != "" && $value == "" && $customerstatus!="")
	{ 
	  	$sql = "select did,acgroup,fylkekode,active from astacdid where fylkekode = '".$customerstatus."'". tablesort_sql($header);
		$result = pager_query($sql, $maxline);
		while ($item = db_fetch_object($result)) {
			if($item->active == 1){
					$imagename = "green_dott1.gif";
				}else{
					$imagename = "red_dott1.gif";
				}

	    	 $rows[] = array( 
			 $item->did.'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $item->acgroup.'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;', $item->fylkekode.'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
			 array('data' => "<IMG BORDER=\"0\" src=\"files/astar/$imagename\">", 'align' => 'center'),
		);
	}
	$output = astcore_list($header, $rows, $noresults = t('No MSN Numbers'), $maxline);
	return $output;
	}
}

