<?php
/*
 * AstBill  -- Billing, Routing and Management software for Asterisk and MySQL using Drupal
 *
 * www.astbill.com
 *
 * Asterisk -- A telephony toolkit for Linux.
 * Drupal   -- An Open source content management platform.
 *
 * 
 * Copyright (C) 2005, AOFFICE NOMINEE SECRETARIES LIMITED, UNITED KINGDOM.
 *
 * Andreas Mikkelborg <adoroar [Guess What?] astartelecom.com>
 * Are Casilla        <areast  [Guess What?] astartelecom.com>
 *
 *
 * This program is free software, distributed under the terms of
 * the GNU General Public License
 *
 * 2005.10.03 Version 0.9.0.8
 * 2005.11.05 Version 0.9.0.10
 * 
 */

/**
* Display help and module information
* @param section which section of the site we're displaying help
* @return help text for section
*/


function astpricelist_help($section='') {
  $output = '';
  switch ($section) {
    case "admin/modules#description":
      $output = t("AstBill Pricelist");
      break;
  }
  return $output;
} // function astentry_help


function astpricelist_menu($may_cache) {
  $items = array();
  $access = user_access('astpricelist can use');
  $items[] = array('path' => 'astpbx/pricelist',
                                  'title' => t('Rate Table'),
                                  'callback' => '_astratetable_all',
                                  'access' => $access);
                                 // 'type' => MENU_CALLBACK);

	// By using the MENU_CALLBACK type, we can register the callback for this
    // path but not have the item show up in the menu; the admin is not allowed
    // to enable the item in the menu, either.

  return $items;
}

/**
* Valid permissions for this module
* @return array An array of valid permissions for the astentry module
* At this point, we'll give permission to anyone who can access site content 
* or administrate the module:
*/
function astpricelist_perm() {
	return array('astpricelist can use');
  // return array('can use astentry');
} // function astentry_perm()


// BEGIN PRICELIST
function _astratetable_all() {
  global $user;

  $edit = $_POST["edit"];
  $op = $_POST["op"];



  switch (($op ? $op : arg(1))) {
    case t('Go'):

    	$sql = db_fetch_object(db_query("SELECT brand FROM astuser WHERE uid = '%s'", $user->uid));
	drupal_goto("astpbx/pricelist/country/".$edit['countrycode']."/".$sql->brand);
	break;
        default:
        if (arg(2) == 'country') {
		if (!is_numeric(arg(3))) {
		drupal_access_denied();
		return;
	} else {
		$value = arg(3);
		$value2 = arg(4);
	}}


    	$output = astratetable_form($where, $value, $value2);
	
    	if (arg(2) == 'country') {
		$where = 'country';
		$output .= astratetable_form($where, $value, $value2);

	}
	
	
  }

  
  if ($where == 'country') {
	  $sql = db_fetch_object(db_query("SELECT country FROM astcountrycode WHERE countrycode = '%s'", $value));
	  $title = $sql->country;
  }
  
  if (empty($title)) {
	  $title = 'Select Country';
  }
  

_astroute_printtheme_best($output, $title);
}


// FORM STUFF
function astratetable_validate($edit) {
  $myerror = 1;
  $errors = array();


  foreach ($errors as $name => $message) {
    form_set_error($name, $message);
  } 
  return $myerror;
}


function astratetable_save($edit) {
  global $user;

}


function astratetable_form($where, $value, $value2) {
	global $user;
	$edit = $_POST["edit"];
	$op = $_POST["op"];



	

if ($where == 'country') {
	
	if (!is_numeric(arg(3))) {
		drupal_access_denied();
		return;
	} else {
		$value = arg(3);
		}

$maxline = 40;


  $header = array(
    array('data' => t('Pattern&nbsp;&nbsp;'), 'field' => 'pattern'),
    array('data' => t('Name&nbsp;&nbsp;'), 'field' => 'routename', 'colspan' => 2),
    array('data' => t('Price&nbsp;&nbsp;'), 'field' => 'price'),
    );


// array('data' => t('operations'), 'colspan' => 2)

    $sql = db_query("SELECT id, pattern, name, round(price, 2) price, brand FROM astpricelist WHERE (countrycode LIKE '".$value."' AND brand LIKE '".$value2."')". tablesort_sql($header));
    
    $sql2 = db_fetch_object(db_query("select currency FROM astbrand WHERE name='%s'", $value2));
    
	$cur = db_fetch_object(db_query("select ratetabledesc FROM astcurrency WHERE currency='%s'", $sql2->currency));
     
  while ($item = db_fetch_object($sql)) {
	  
	  	$rows[] = array(
		$item->pattern.'&nbsp;&nbsp;',
		$item->name.'&nbsp;&nbsp;',
		$cur->ratetabledesc.'&nbsp;',
		array('data' => $item->price, 'align' => 'right')

		);
  }

  $pager = theme('pager', null, $maxline, 0, tablesort_pager()); 
  if (!empty($pager)) {
    $rows[] = array(array('data' => $pager, 'colspan' => 8));
  }


 $output .= (count($rows) == 0) ? t('No records.') : theme('table', $header, $rows);


 return $output;
	

}

if (empty($where)) {
	
	$countrylist = db_query("SELECT countrycode, country FROM astcountrycode WHERE usstate is null order by country");
	$countryout = array();
  
	
	while ($model = db_fetch_object($countrylist)) {
		array_push2($countryout, $model->country, $model->countrycode);
	}


	if (empty($value)) {
	$sql = db_fetch_object(db_query("SELECT countryprefix FROM astuser WHERE uid = '%d'", $user->uid));
	$defaultcountry = $sql->countryprefix;
	} else {
		$defaultcountry = $value;
		
	}
	
	if (empty($value2)) {
	$defaultbrand = 'default';
	} else {
		$defaultbrand = $value2;
		
	}
	
	
	$group .= form_select(t("Select Country"), "countrycode", $defaultcountry, $countryout);
	$group .= form_submit(t('Go'));
	
	return form($group);
}



}



// END FORM STUFF
// END PRICELIST


// ##########################################################################################################


function _astpricelist_printtheme_best($page_content, $title) {
$output = '<div class="node "><table width="100%" border="0" cellpadding="0" cellspacing="0"><tr><td class="corner_img_l">&#160;</td><td><h1 class="nodetitle">'.$title.'</h1></td><td class="corner_img_r">&#160;</td></tr></table></div>';

  $output .= '<div class="nodecontent">' . $page_content . "</div>\n";
  // $output .= '<div class="astentry">' . $page_content . "</div>\n";
  print theme("page", $output);
}

function astpricelist_currency($cur) {
	$output = $cur;
	if ($cur == "E") { $output = "?"; }
	if ($cur == "G") { $output = "GBP"; }
	// $output = "?";
	return $output;
}

// ##########################################################################################################